# Generated by Django 5.2.7 on 2025-11-02 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10, unique=True, verbose_name='Ders Kodu')),
                ('course_name', models.CharField(max_length=255, verbose_name='Ders Adı')),
                ('syllabus', models.TextField(blank=True, null=True, verbose_name='Ders Syllabus (İzlenç)')),
                ('instructors', models.ManyToManyField(related_name='courses_taught', to=settings.AUTH_USER_MODEL, verbose_name='Derse Atanan Hocalar')),
            ],
        ),
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Öğrenim Çıktısı Açıklaması')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcomes', to='course_management.course', verbose_name='Ders')),
            ],
            options={
                'verbose_name': 'Öğrenim Çıktısı',
                'verbose_name_plural': 'Öğrenim Çıktıları',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Öğrenci'), ('instructor', 'Öğretim Görevlisi'), ('department_head', 'Bölüm Başkanı')], max_length=20, verbose_name='Kullanıcı Rolü')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Değerlendirme Adı (örn: Vize, Final, Proje)')),
                ('percentage', models.PositiveSmallIntegerField(verbose_name='Ağırlık Yüzdesi (%)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_components', to='course_management.course', verbose_name='Ders')),
            ],
            options={
                'verbose_name': 'Değerlendirme Bileşeni',
                'verbose_name_plural': 'Değerlendirme Bileşenleri',
                'unique_together': {('course', 'name')},
            },
        ),
    ]
