# Generated by Django 5.2.7 on 2025-11-02 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'profile__role': 'student'}, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL, verbose_name='Derse Kayıtlı Öğrenciler'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(limit_choices_to={'profile__role': 'instructor'}, related_name='courses_taught', to=settings.AUTH_USER_MODEL, verbose_name='Derse Atanan Hocalar'),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Alınan Not')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='course_management.evaluationcomponent', verbose_name='Değerlendirme Bileşeni')),
                ('student', models.ForeignKey(limit_choices_to={'profile__role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL, verbose_name='Öğrenci')),
            ],
            options={
                'verbose_name': 'Not',
                'verbose_name_plural': 'Notlar',
                'unique_together': {('student', 'component')},
            },
        ),
    ]
