# Generated by Django 5.2.8 on 2025-11-14 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0005_programoutcome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OutcomeWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Ağırlık (1-5)')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_weights', to='course_management.evaluationcomponent', verbose_name='Değerlendirme Bileşeni')),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_weights', to='course_management.learningoutcome', verbose_name='Learning Outcome')),
            ],
            options={
                'verbose_name': 'Outcome Ağırlığı',
                'verbose_name_plural': 'Outcome Ağırlıkları',
                'unique_together': {('component', 'outcome')},
            },
        ),
    ]
