# Generated by Django 5.2.8 on 2025-11-15 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0006_student_outcomeweight'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningOutcomeProgramOutcomeWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Ağırlık (1-5)')),
                ('learning_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_outcome_weights', to='course_management.learningoutcome', verbose_name='Learning Outcome')),
                ('program_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcome_weights', to='course_management.programoutcome', verbose_name='Program Outcome')),
            ],
            options={
                'verbose_name': 'Learning Outcome - Program Outcome Ağırlığı',
                'verbose_name_plural': 'Learning Outcome - Program Outcome Ağırlıkları',
                'unique_together': {('learning_outcome', 'program_outcome')},
            },
        ),
    ]
